version: '3.8'
services:

  # PHP-FPM
  php:
    build: ./php/
    container_name: phpfpm 
    restart: unless-stopped
    expose: 
      - 9000
    environment:
      TZ: ${TZ}
    depends_on:
      - mysql
    tty: true
    volumes:
      - ./www/html/:/var/www/html/
    networks:
      - php

  # NGINX SERVICE
  nginx:
    build: ./nginx/
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./www/html/:/var/www/html/
    depends_on:
      - php 
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}
    networks:
      - php
  
  # MySQL DATABASE
  mysql:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      # Note: ports are exposed as I'm hitting the database from an external application
      # Dissable for better security if apps will be accessing it interally.
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql/
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - php

networks:
  php:

volumes:
  db:

